# Generated by Django 4.1.6 on 2023-02-09 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='books',
        ),
    ]
